name: Deploy Prod App
on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_ORG_API_TOKEN }}
    runs-on: ubuntu-latest
    concurrency: prod
    environment: prod
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Set secrets for app
        run: |
          flyctl secrets set ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} --stage
          flyctl secrets set S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} --stage
          flyctl secret sset S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY } --stage
      - name: Deploy Prod app
        run: flyctl deploy --remote-only
